name: Tex
on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
      - uses: actions/upload-artifact@v2
        with:
          name: Compiled
          path: thesis.pdf
      - name: Release PDF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: thesis.pdf
